rules:
    property-sort-order: 0
    force-element-nesting: 0
    nesting-depth:
        - 1
        - max-depth: 4
    no-important: 0
    no-qualifying-elements: 0
    leading-zero:
        - 1
        - include: true